### ISSUE TITLE
Cannot add default metrics in Plumber API

### ISSUE THREAD

**Issue by marcelo-pires-dsa** [atheriel/openmetrics#12]
Hi all, I trying to register the default metrics for my Plumber API, but when calling register_default_metrics I get the error below

Error in registry$collector("default") (server.R#9): attempt to apply non-function.

This is how I am calling it in my code.

´´´code
library(plumber)
library(openmetrics)

root <- pr()

v1 <- pr("./routers/api/v1/routes.R")

root %>%
  register_plumber_metrics() %>%
  register_default_metrics() %>%
  pr_mount(path = "/api/v1/", router = v1) %>%
  pr_run(port = 5000)
```

**Comment by atheriel** [comment]
You can't pass a Plumber API into `register_default_metrics()`, I'm afraid.

But it should be possible to do use both Plumber and default metrics. Check out the documentation for some examples.
