### ISSUE TITLE
Compatibility with plumber 1.0.0

### ISSUE THREAD

**Issue by BekyP** [atheriel/openmetrics#8]
Hi,

after I switched to plumber 1.0.0, openmetrics::register_plumber_metrics() stopped working with following error message:
```
Error in openmetrics::register_plumber_metrics(pr) : 
   inherits(app, "plumber") is not TRUE
```

my code: 

```
# Run API ----
pr <- plumber::plumb("plumber.R")
pr <- openmetrics::register_plumber_metrics(pr)

pr <- pr_set_debug(pr, debug = TRUE)
pr$run(host = '0.0.0.0', port = 8000)
```

Any suggestions on how to fix this? Or do I need to wait for next release of openmetrics?

**Comment by atheriel** [comment]
This appears to be due to [a breaking change in Plumber](https://www.rplumber.io/news/#breaking-changes). It think it will require a new release to fix, unfortunately; not sure why their reverse dependency checking didn't catch it.

**Comment by atheriel** [comment]
@BekyP The CRAN version should now contain a fix.

**Comment by BekyP** [comment]
Thanks for the fix, I`ll check it
