### ISSUE TITLE
Error Key /metrics already in use raised in shiny

### ISSUE THREAD

**Issue by jpenekusu** [atheriel/openmetrics#9]
First of all, the sample code used bellow is from Rshiny web site.

When shiny app is started from server.R (see the code bellow), an exception is raised after opening more than one session to the R apps.

**Below in the content of the file server.R:**

```
library(shiny)
library(openmetrics)
source("ui.R")

# Define server logic required to generate and plot a random distribution
server <- function(input, output) {

  # Expression that generates a plot of the distribution. The expression
  # is wrapped in a call to renderPlot to indicate that:
  #
  #  1) It is "reactive" and therefore should be automatically 
  #     re-executed when inputs change
  #  2) Its output type is a plot 
  #
  output$distPlot <- renderPlot({
        
    # generate an rnorm distribution and plot it
    dist <- rnorm(input$obs)
    hist(dist)
  }) 

  meows <- counter_metric("meows", "Heard around the house.", labels = "cat")
  meows$inc(cat = "Shamus") # Count one meow from Shamus.
  meows$inc(3, cat = "Unknown") # Count three meows of unknown origin.

  thermostat <- gauge_metric("thermostat", "Thermostat display.")
  thermostat$set(21.3) # Read from the display...
  thermostat$dec(2) # ... and then turn it down 2 degrees.

  temperature <- histogram_metric(
    "temperature", "Ambient room temperature measurements.",
    buckets = c(10, 15, 20, 22, 25), room = "kitchen"
  )
  set.seed(9090)
  # Simulate taking ambient temperature samples.
  for (measure in rnorm(20, mean = 21.5)) {
    temperature$observe(measure, room = sample(c("kitchen", "bathroom"), 1))
  }
  **app <- shinyApp(ui, server)
  register_shiny_metrics(app)
  register_default_metrics()
  app**  
}
```

Here the complete log error. Could you advice why the /metrics context is still in use between different sessions ?

Warning: Error in handlers$add: Key /metrics already in use
--
  | 51: stop
  | 50: handlers$add
  | 49: handlerManager$addHandler
  | 48: register_shiny_metrics
  | 47: server [/opt/app-root/src/server.R#40]
  | Error in handlers$add(handler, key, tail) : Key /metrics already in use

**Comment by atheriel** [comment]
I don't think you should be using `shinyApp()` inside of a `server.R` file. `register_shiny_metrics()` must be called only once per app, not once per session, as it modifies the application itself. I'm not sure what the precise solution for you will be, but you can check out [Shiny's documentation](https://shiny.rstudio.com/articles/app-formats.html).

Edit: I would suggest using an `app.R` file.
